language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - kalakris-cmake
        packages:
        - g++-5
        - cmake
    env:
      - _CC=gcc-5
      - _CXX=g++-5
  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
        - llvm-toolchain-precise-3.8
        - ubuntu-toolchain-r-test
        - kalakris-cmake
        packages:
        - clang-3.8
        - cmake
    env:
      - _CC=clang-3.8
      - _CXX=clang-3.8
  - os: osx
    osx_image: xcode6.4
    compiler: clang
    env:
  - os: osx
    osx_image: xcode7.3
    compiler: clang
    env:
  - os: osx
    osx_image: xcode8
    compiler: clang
    env:


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -sL https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz | tar xvz ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$PWD/cmake-3.5.2-Linux-x86_64/bin:$PATH ; fi

script:
  - mkdir build
  - cd build
  - export CC=$_CC
  - export CXX=$_CXX
  - cmake .. $CMAKE_ARGS -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release
