language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - cmake
        - kalakris-cmake
    env:
      - CC=gcc-5
      - CXX=g++-5
      - CMAKE_ARGS=
  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
        - llvm-toolchain-precise-3.8
        - ubuntu-toolchain-r-test
        - kalakris-cmake
        packages:
        - clang-3.8
        - cmake
        - ninja-build
    env:
      - CC=clang-3.8
      - CXX=clang++-3.8
      - CMAKE_ARGS=
  - os: osx
    compiler: clang
    env:
      - CC=clang
      - CXX=clang++
      - CMAKE_ARGS=

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -sL https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz | tar xvz ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$PWD/cmake-3.5.2-Linux-x86_64/bin:$PATH ; fi

script:
  - mkdir build
  - cd build
  - export CC=$CC
  - export CXX=$CXX
  - cmake .. $CMAKE_ARGS
  - cmake --build . --config Release
