language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - cmake
        - kalakris-cmake
    env:
      - CC=gcc-5
      - CXX=g++-5
  - os: linux
    compiler: clang
    addons:
      apt:
        sources:
        - llvm-toolchain-precise-3.8
        - ubuntu-toolchain-r-test
        - kalakris-cmake
        packages:
        - clang-3.8
        - cmake
        - ninja-build
    env:
      - CC=clang-3.8
      - CXX=clang++-3.8
  - os: osx
    compiler: clang
    env:

before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake ninja; fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config Release
