language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - ninja-build
        - g++-6
    env: PLATFORM=linux COMPILER=gcc TOOLCHAIN=linux-gcc-libstdc++
  - os: linux
    compiler: clang
    # addons:
    #   apt:
    #     sources:
    #     - llvm-toolchain-precise-3.8
    #     - ubuntu-toolchain-r-test
    #     packages:
    #     - clang-3.8
    env: PLATFORM=linux COMPILER=clang TOOLCHAIN=linux-clang-libc++
  # - os: osx
  #   osx_image: xcode6.4
  #   compiler: clang
  #   env: PLATFORM=darwin TOOLCHAIN=darwin-clang-libc++
  # - os: osx
  #   osx_image: xcode7.3
  #   compiler: clang
  #   env: PLATFORM=darwin TOOLCHAIN=darwin-clang-libc++
  # - os: osx
  #   osx_image: xcode8
  #   compiler: clang
  #   env: PLATFORM=darwin TOOLCHAIN=darwin-clang-libc++

before_install:
  - PLATFORM_COMPILER=$PLATFORM-$COMPILER
#  - PLATFORM_COMPILER_STDLIB=$PLATFORM_COMPILER-$STDLIB
  - if [ -f tools/$PLATFORM.sh ]; then . ./tools/$PLATFORM.sh ; fi
  - if [ -f tools/$PLATFORM_COMPILER.sh ]; then . ./tools/$PLATFORM_COMPILER.sh ; fi

script:
  - ls -l
  - echo $PATH
  - export PATH=$PWD/bin:$PATH
  - export LD_LIBRARY_PATH=$PWD/lib
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=../tools/$TOOLCHAIN.cmake
  - cmake --build . --config Release
